[Feat] Upload 패키지 구조 변경 및 Image 저장 API 구현, 문서화
codestates-seb/seb40_main_032 pull request #139
Opened 2022-11-19 05:23 UTC by hipopotamus

Upload 패키지 구조 변경 및 Image 저장 API를 구현하고 문서화하였습니다.

기존에 이미지 저장을 한번에 했던 부분은 추후에 수정할 계획입니다(프로필 이미지 수정)

2022-11-19 13:45 UTC, Cutaku requested changes

2022-11-19 13:45 UTC, Cutaku commented on back/src/main/java/travelRepo/global/image/repository/ImageRepository.java
> +}
path가 S3ImageRepository 에선 쓰이지 않는데 FolderImageRepository에 넣고 save는 image만 받는게 좋을 것 같습니다. 

save 메서드 쓰이는 곳마다 path를 정의해야할 필요도 없어보이고요.

2022-11-19 14:43 UTC, hipopotamus commented on back/src/main/java/travelRepo/global/image/repository/ImageRepository.java
> +}
![image](https://user-images.githubusercontent.com/77265289/202855297-f0fed6fc-2d1b-4144-b058-7a385e6c0fab.png)

s3에 path를 사용하도록 수정했습니다.

저는 파일을 저장할 때 path를 받는게 맞다고 생각합니다. 
왜냐하면 파일을 저장할 때 path는 반드시 필요되는 요소이면서 변수이기도 하기 때문입니다.
지금은 편의상 하나의 폴더 혹은 S3 경로에 모든 이미지를 저장하고 있기 때문에, path를 repository에서 고정시켜 놓고 사용해도 문제가없습니다.
하지만 이렇게 메서드를 작성하면 save라는 메서드는 하나의 고정된 path에만 파일을 저장하는 메서드가 됩니다. 
만약 profile 이미지와  board 이미지를 s3에서 다른 경로에 분할해서 저장하고 싶은데 path를 받지 않는 방식으로 한다면 profileImageSave, boardImageSave와 같이 각 경로에 파일을 저장하는 메서드를 작성해야 할것입니다.
이런 방식은 ImageRepository를 상속받는 형태와 맞지 않기도하고, service의 영역에서 처리되어야 할 문제(path를 결정하는것)라고 생각합니다.

저는 파일을 저장할 때 저장할 경로를 받는게 자연스럽다고 생각합니다. 왜냐하면 다른 서비스를 사용할 때에도 파일을 저장할때 기본 저장 경로가 있지만 저장될 경로를 저희가 지정할수 있기 때문입니다. 
결론적으로 저는 path가 변수이기 때문에 파일을 저장할때 인자로 받아야될 부분이라고 생각합니다.

2022-11-20 05:16 UTC, Cutaku approved these changes

2022-11-20 05:17 UTC, merged