[Feat] 좋아요한 게시글 조회 API 구현
codestates-seb/seb40_main_032 pull request #205
Opened 2022-11-24 11:13 UTC by Cutaku

유저가 좋아요한 게시글을 조회하는 API가 없어 만들었습니다.

일단 없어서 급하게 만들었는데 먼저 PR하고 테스트&수정 하겠습니다.

2022-11-24 13:10 UTC, hipopotamus requested changes

2022-11-24 13:10 UTC, hipopotamus commented on back/src/main/java/travelRepo/domain/likes/likesRepository/LikesRepository.java
> +
db에서 board를 조회하는것이 목적이니까 like에서 가져오기보다는 board에 like를 조인해서 찾는게 더 자연스럽고 서비스 메서드에서 연산도 한번 줄일 수 있을 거 같습니다
```sql
select board from Board board join Likes likes where likes.account.id =:accountId
```
account도 entityGraph로 한번에 가져오면서 이런식으로 조회하는것이 좀 더 괜찮을거 같습니다.

2022-11-25 00:07 UTC, Cutaku commented on back/src/main/java/travelRepo/domain/likes/likesRepository/LikesRepository.java
> +
likes 쪽에서 조회한 이유는 likes를 기준으로 정렬시키기 위해서 였습니다.  최근에 좋아요를 누른 게시글이 우선적으로 뜨는게 맞을 것 같아서요

지금 board쪽에서 조회할 수 있도록 해보는 중인데 시간이 좀 필요할 것 같아서 우선 반영해주시면 좋을 것 같습니다. 프론트 쪽에서 api 쓰신다고 하셔서요

2022-11-25 03:04 UTC, hipopotamus approved these changes

2022-11-25 03:04 UTC, merged